### ISSUE TITLE
Isha Time Wrong. Rest of them correct.

### ISSUE THREAD

**Issue by buildwithmalik** [prayer-timetable/adhan_dart#1]
Brother the time for isha seems a bit off.

Correct time is 20:16 and it is showing 18:50 which is even earlier than maghrib.

```
Coordinates coordinates = Coordinates(17.9950,78.0267); //Hyderabad Coordinates [Asia/Kolkata]
CalculationParameters calculationParameters = CalculationMethod.Karachi();
PrayerTimes prayerTimes = new PrayerTimes(coordinates, DateTime.now(), calculationParameters);

print(prayerTimes.fajr.toLocal());
print(prayerTimes.dhuhr.toLocal());
print(prayerTimes.asr.toLocal());
print(prayerTimes.maghrib.toLocal());
print(prayerTimes.isha.toLocal());
```

OUTPUT :

```
I/flutter (19670): 2020-06-25 04:22:00.000
I/flutter (19670): 2020-06-25 12:20:00.000
I/flutter (19670): 2020-06-25 15:42:00.000
I/flutter (19670): 2020-06-25 18:54:00.000
I/flutter (19670): 2020-06-25 18:50:00.000
Reloaded 1 of 675 libraries in 1,160ms

```
All timings are correct except isha time. Please look into the matter. Jazkallah

**Comment by ench0** [comment]
Will do, it was fine while I was testing with custom calc parameters, but haven't yet been able to check the presets yet. Thanks for spotting it.

**Comment by buildwithmalik** [comment]
> Will do, it was fine while I was testing with custom calc parameters, but haven't yet been able to check the presets yet. Thanks for spotting it.

I built an application for prayer times called "Timeforsalah" with flutter, you can find it on playstore. I was familiar with java so i used the java version of adhan.js by using platform channels. 

I tried to convert it in dart but it was too complex for me. Can't wait to have it in dart so that an IOS version could also be possible. Great work !

**Comment by ench0** [comment]
I got it, it was an issue with all calculation methods that did not have custom isha angle. Basically a typo in code where ishaAngle was set to ishaInterval. Now it should work for all:
```
import 'package:adhan/adhan.dart';

main() {
  Coordinates coordinates =
      Coordinates(17.3850, 78.4867); //Hyderabad Coordinates [Asia/Kolkata]
  CalculationParameters calculationParameters = CalculationMethod.Karachi();
  PrayerTimes prayerTimes =
      PrayerTimes(coordinates, DateTime.now(), calculationParameters);

  int timezoneAdj = (5.5 * 60).toInt();

  print(prayerTimes.fajr.add(Duration(minutes: timezoneAdj)));
  print(prayerTimes.dhuhr.add(Duration(minutes: timezoneAdj)));
  print(prayerTimes.asr.add(Duration(minutes: timezoneAdj)));
  print(prayerTimes.maghrib.add(Duration(minutes: timezoneAdj)));
  print(prayerTimes.isha.add(Duration(minutes: timezoneAdj)));
}
```

Result:
```
2020-06-26 04:22:00.000Z
2020-06-26 12:20:00.000Z
2020-06-26 15:43:00.000Z
2020-06-26 18:54:00.000Z
2020-06-26 20:16:00.000Z
```

I had to use timezone adjustment in the above example (as my local time is UTC+1), but of course the proper way would be by using _timezone_ package.

**Comment by buildwithmalik** [comment]
Great job! Cant wait to implement the library !
