### ISSUE TITLE
some CalculationMethod throws error

### ISSUE THREAD

**Issue by mourad-mouzai** [prayer-timetable/adhan_dart#2]
salem bro,
CalculationMethod.UmmAlQura();
and
CalculationMethod.Qatar();
throws error: 
_TypeError (type 'double' is not a subtype of type 'int')
thanks for looking at this problem.

**Comment by ench0** [comment]
Thanks for spotting. It was an issue with ishaInterval being declared as double instead of int. Tehran method was also using it, but because it was set as '0' it did not throw an error. Should work now and update pending.

**Comment by ench0** [comment]
Fixed

**Comment by mourad-mouzai** [comment]
Thanks a lot bro, peace be upon you!
