### ISSUE TITLE
Add Ishraq, Chast and Prohibated Prayer Time

### ISSUE THREAD

**Issue by md-rifatkhan** [prayer-timetable/adhan_dart#7]
[Enhancement] it will better to add Ishraq, Chast, Noon time, or directly Prohibated Time,

**Comment by davidsonkillian** [comment]
Ishraq: Ishraq prayer is performed approximately 15-20 minutes after sunrise. It is a recommended prayer in Islam, but not obligatory. The time for Ishraq begins when the sun rises to the height of a spear above the horizon and ends when it is fully risen.

Chast: Chast prayer is the optional prayer performed after the sun has risen significantly, [this](https://theprayertimings.com/namaz-times-in-karachi/) typically around late morning to noon. It is also known as Salat ad-Duha, which is offered as a voluntary act of worship.
